#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEPLOY_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

ENV_FILE="${ENV_FILE:-$DEPLOY_DIR/.env}"
FORCE="${FORCE:-false}"

is_true() {
  case "${1:-}" in
    1|true|TRUE|yes|YES|on|ON) return 0 ;;
    *) return 1 ;;
  esac
}

usage() {
  cat <<'EOF'
usage: generate-private-env.sh

Creates a local private Hetzner staging .env with generated secrets and safe
defaults. The generated file is intentionally gitignored and should be edited
on the real staging host before production evidence is collected.

Environment:
  ENV_FILE=/path/to/.env      Output path. Defaults to deployment/hetzner-staging/.env.
  FORCE=true                 Overwrite an existing env file.
  FORGEJO_DOMAIN=host        Override the local staging host name.
  FORGEJO_ROOT_URL=url       Override the Forgejo root URL.
  ELIZA_CLOUD_OIDC_ISSUER_URL=url
  ELIZA_CLOUD_OIDC_DISCOVERY_URL=url
  FORGEJO_IMAGE=image:tag
  MERGE_STEWARD_IMAGE=image:tag
  FORGEJO_RUNNER_IMAGE=image:tag
EOF
}

secret_hex() {
  local bytes="${1:-32}"
  openssl rand -hex "$bytes"
}

require_command() {
  command -v "$1" >/dev/null 2>&1 || {
    printf 'error: missing required command: %s\n' "$1" >&2
    exit 1
  }
}

main() {
  if [[ "${1:-}" == "--help" || "${1:-}" == "-h" ]]; then
    usage
    exit 0
  fi

  require_command openssl

  if [[ -e "$ENV_FILE" ]] && ! is_true "$FORCE"; then
    printf 'error: %s already exists; set FORCE=true to overwrite\n' "$ENV_FILE" >&2
    exit 1
  fi

  local domain root_url ssh_domain oidc_issuer oidc_discovery
  domain="${FORGEJO_DOMAIN:-git.eliza.localhost}"
  root_url="${FORGEJO_ROOT_URL:-https://${domain}/}"
  ssh_domain="${FORGEJO_SSH_DOMAIN:-$domain}"
  oidc_issuer="${ELIZA_CLOUD_OIDC_ISSUER_URL:-https://cloud.eliza.localhost}"
  oidc_discovery="${ELIZA_CLOUD_OIDC_DISCOVERY_URL:-${oidc_issuer%/}/.well-known/openid-configuration}"

  local db_password recovery_password forgejo_secret internal_token oauth_secret
  local forgejo_client_secret steward_token webhook_secret api_token receipt_secret
  db_password="$(secret_hex 32)"
  recovery_password="$(secret_hex 32)"
  forgejo_secret="$(secret_hex 32)"
  internal_token="$(secret_hex 32)"
  oauth_secret="$(secret_hex 32)"
  forgejo_client_secret="$(secret_hex 32)"
  steward_token="$(secret_hex 32)"
  webhook_secret="$(secret_hex 32)"
  api_token="$(secret_hex 32)"
  receipt_secret="$(secret_hex 32)"

  mkdir -p "$(dirname "$ENV_FILE")"
  umask 077
  cat >"$ENV_FILE" <<EOF
# Generated by deployment/hetzner-staging/scripts/generate-private-env.sh.
# Keep this file private. It is for local/staging validation and is not
# production evidence by itself.

COMPOSE_PROJECT_NAME=eliza-forgejo-staging

FORGEJO_IMAGE=${FORGEJO_IMAGE:-codeberg.org/forgejo/forgejo:15}
POSTGRES_IMAGE=${POSTGRES_IMAGE:-postgres:16-alpine}
MERGE_STEWARD_IMAGE=${MERGE_STEWARD_IMAGE:-eliza/merge-steward:staging-local}
FORGEJO_RUNNER_IMAGE=${FORGEJO_RUNNER_IMAGE:-data.forgejo.org/forgejo/runner:12}
FORGEJO_RUNNER_DIND_IMAGE=${FORGEJO_RUNNER_DIND_IMAGE:-docker:28-dind}

FORGEJO_DOMAIN=$domain
FORGEJO_ROOT_URL=$root_url
FORGEJO_SSH_DOMAIN=$ssh_domain
FORGEJO_PUBLIC_SSH_PORT=22

FORGEJO_HTTP_BIND=127.0.0.1
FORGEJO_HTTP_PORT=3000
FORGEJO_SSH_BIND=127.0.0.1
FORGEJO_SSH_PORT=2222

FORGEJO_UID=1000
FORGEJO_GID=1000

FORGEJO_RECOVERY_ADMIN_USERNAME=eliza-recovery-admin
FORGEJO_RECOVERY_ADMIN_EMAIL=eliza-recovery-admin@$domain
FORGEJO_RECOVERY_ADMIN_PASSWORD=$recovery_password

FORGEJO_DB_NAME=forgejo
FORGEJO_DB_USER=forgejo
FORGEJO_DB_PASSWORD=$db_password

FORGEJO_SECRET_KEY=$forgejo_secret
FORGEJO_INTERNAL_TOKEN=$internal_token
FORGEJO_OAUTH2_JWT_SECRET=$oauth_secret

FORGEJO_ACTIONS_ENABLED=true
FORGEJO_ACTIONS_URL=https://code.forgejo.org
FORGEJO_ACTION_LOG_RETENTION_DAYS=14
FORGEJO_ACTION_ARTIFACT_RETENTION_DAYS=14

FORGEJO_MAIL_ENABLED=false
FORGEJO_REGISTER_EMAIL_CONFIRM=false
FORGEJO_MAIL_PROTOCOL=smtps
FORGEJO_SMTP_ADDR=
FORGEJO_SMTP_PORT=465
FORGEJO_MAIL_FROM=
FORGEJO_SMTP_USER=
FORGEJO_SMTP_PASSWORD=

FORGEJO_RUNNER_INSTANCE=$root_url
FORGEJO_RUNNER_NAME=eliza-staging-docker-1
FORGEJO_RUNNER_LABELS=docker:docker://node:24-bookworm,node-24:docker://node:24-bookworm,ubuntu-latest:docker://node:24-bookworm
FORGEJO_RUNNER_REGISTRATION_TOKEN=

FORGEJO_OIDC_AUTH_NAME=elizacloud
FORGEJO_OIDC_SCOPES="openid email profile groups"
FORGEJO_OIDC_SKIP_LOCAL_2FA=true
FORGEJO_OAUTH2_ENABLE_AUTO_REGISTRATION=true
FORGEJO_OAUTH2_REGISTER_EMAIL_CONFIRM=false
FORGEJO_OAUTH2_USERNAME=nickname
FORGEJO_OAUTH2_ACCOUNT_LINKING=login
FORGEJO_OIDC_REQUIRED_CLAIM_NAME=tenant
FORGEJO_OIDC_REQUIRED_CLAIM_VALUE=eliza
FORGEJO_OIDC_GROUP_CLAIM_NAME=groups
FORGEJO_OIDC_ADMIN_GROUP=eliza-admins
FORGEJO_OIDC_RESTRICTED_GROUP=eliza-agents
ELIZA_CLOUD_OIDC_ISSUER_URL=$oidc_issuer
ELIZA_CLOUD_OIDC_DISCOVERY_URL=$oidc_discovery
ELIZA_CLOUD_OIDC_JWKS_URL=
ELIZA_CLOUD_FORGEJO_CLIENT_ID=eliza-hub-staging
ELIZA_CLOUD_FORGEJO_CLIENT_SECRET=$forgejo_client_secret
ELIZA_CLOUD_STEWARD_AUDIENCE=eliza-merge-steward

FORGEJO_THEMES=forgejo-auto,forgejo-light,forgejo-dark,eliza,eliza-light
FORGEJO_DEFAULT_THEME=eliza

MERGE_STEWARD_HTTP_BIND=127.0.0.1
MERGE_STEWARD_HTTP_PORT=8080
MERGE_STEWARD_DEPLOYMENT_MODE=production
MERGE_STEWARD_DATABASE_URL=postgres://forgejo:$db_password@postgres:5432/forgejo
MERGE_STEWARD_QUEUE_STORE_PATH=
FORGEJO_STEWARD_USERNAME=eliza-merge-steward
FORGEJO_STEWARD_EMAIL=eliza-merge-steward@$domain
FORGEJO_STEWARD_TOKEN=$steward_token
FORGEJO_WEBHOOK_SECRET=$webhook_secret
MERGE_STEWARD_API_AUTH_REQUIRED=true
MERGE_STEWARD_API_TOKEN=$api_token
MERGE_STEWARD_METRICS_ENABLED=true
MERGE_STEWARD_METRICS_AUTH_REQUIRED=true
MERGE_STEWARD_OIDC_ENABLED=true
MERGE_STEWARD_OIDC_REQUIRED_ROLES=steward,maintainer
MERGE_STEWARD_OIDC_REQUIRED_GROUPS=eliza-team
MERGE_STEWARD_OIDC_ADMIN_ROLES=steward-admin
MERGE_STEWARD_OIDC_ADMIN_GROUPS=eliza-admins
MERGE_STEWARD_MAX_BODY_BYTES=1048576
MERGE_STEWARD_WEBHOOK_REQUIRE_DELIVERY_ID=true
MERGE_STEWARD_EVENT_GATE_ENABLED=true
MERGE_STEWARD_EVENT_GATE_REPOSITORIES=elizaos/eliza
MERGE_STEWARD_EVENT_GATE_TRUSTED_ACTORS=
MERGE_STEWARD_EVENT_GATE_ALLOWED_KINDS=
MERGE_STEWARD_EVENT_GATE_COMMAND_PREFIXES=/eliza,/steward
MERGE_STEWARD_EVENT_GATE_ALLOW_FORKS=false
MERGE_STEWARD_REQUIRE_AGENT_RUN_RECEIPT=false
MERGE_STEWARD_REQUIRE_VERIFIED_AGENT_RUN_RECEIPT=false
MERGE_STEWARD_AGENT_RUN_RECEIPT_SECRET=$receipt_secret
MERGE_STEWARD_REQUIRE_WORK_RESERVATION_FOR_AGENT_PRS=false
MERGE_STEWARD_REQUIRE_WORK_ITEM_FOR_AGENT_PRS=false
MERGE_STEWARD_REQUIRE_AGENT_BRANCH_NAMESPACE=false
MERGE_STEWARD_AGENT_BRANCH_NAMESPACE_PREFIX=agent
MERGE_STEWARD_REQUIRE_AGENT_IDENTITY_REGISTRY=false
MERGE_STEWARD_AGENT_IDENTITY_REGISTRY=eliza-smoke-agent
MERGE_STEWARD_AGENT_RUN_RECEIPT_SECRET_ENV=MERGE_STEWARD_AGENT_RUN_RECEIPT_SECRET
FORGEJO_FEEDBACK_ENABLED=false
FORGEJO_FEEDBACK_DRY_RUN=true
FORGEJO_FEEDBACK_LABELS=true
FORGEJO_FEEDBACK_COMMENTS=true
FORGEJO_ENRICHMENT_ENABLED=false
FORGEJO_PROTECTED_BRANCHES=main,develop
FORGEJO_REQUIRED_CHECKS=
FORGEJO_ENRICHMENT_PAGE_LIMIT=50
FORGEJO_ENRICHMENT_MAX_PAGES=10
MERGE_STEWARD_INTEGRATION_ENABLED=false
MERGE_STEWARD_INTEGRATION_DRY_RUN=true
MERGE_STEWARD_INTEGRATION_EXECUTOR=none
MERGE_STEWARD_INTEGRATION_BATCHING=false
MERGE_STEWARD_INTEGRATION_BRANCH_PREFIX=eliza-queue
MERGE_STEWARD_INTEGRATION_BRANCH_MODE=reset
MERGE_STEWARD_INTEGRATION_ALLOW_EMPTY_CHECKS=false
MERGE_STEWARD_INTEGRATION_REMOTE_URL=
MERGE_STEWARD_INTEGRATION_WORK_DIR=/state/git
MERGE_STEWARD_INTEGRATION_GIT_BINARY=git
MERGE_STEWARD_INTEGRATION_PUSH_BRANCH=false
MERGE_STEWARD_INTEGRATION_MERGE_METHOD=merge
MERGE_STEWARD_INTEGRATION_DELETE_BRANCH_AFTER_MERGE=false
MERGE_STEWARD_INTEGRATION_MERGE_TITLE=
MERGE_STEWARD_INTEGRATION_MERGE_MESSAGE=
MERGE_STEWARD_CHECK_POLL_ATTEMPTS=1
MERGE_STEWARD_CHECK_POLL_INTERVAL_MS=0
MERGE_STEWARD_WORKER_ENABLED=false
MERGE_STEWARD_WORKER_ID=merge-steward-worker
MERGE_STEWARD_WORKER_POLL_INTERVAL_MS=5000
MERGE_STEWARD_WORKER_CONFIRM_LIVE_EXECUTION=false
MERGE_STEWARD_WORKER_MAX_CONSECUTIVE_ERRORS=5
MERGE_STEWARD_WORKER_LEASE_ENABLED=true
MERGE_STEWARD_WORKER_LEASE_ID=merge-queue
MERGE_STEWARD_WORKER_LEASE_TTL_MS=30000
MERGE_STEWARD_WORKER_LEASE_HEARTBEAT_INTERVAL_MS=10000
MERGE_STEWARD_WORKER_STALE_QUEUE_ITEM_MS=120000
EOF

  chmod 600 "$ENV_FILE"
  printf 'generated private staging env: %s\n' "$ENV_FILE"
}

main "$@"
