const TELEGRAM_PLUGIN = {
  id: "telegram",
  name: "Telegram",
  description: "Telegram bot connector",
  enabled: false,
  configured: false,
  envKey: null,
  category: "connector",
  source: "bundled",
  icon: "T",
  parameters: [
    {
      key: "TELEGRAM_BOT_TOKEN",
      type: "string",
      description: "Bot token from @BotFather",
      required: true,
      sensitive: true,
      currentValue: null,
      isSet: false,
    },
    {
      key: "TELEGRAM_API_ROOT",
      type: "string",
      description: "API root override",
      required: false,
      sensitive: false,
      currentValue: null,
      isSet: false,
    },
    {
      key: "TELEGRAM_ALLOWED_CHATS",
      type: "string",
      description: "Comma-separated chat allowlist",
      required: false,
      sensitive: false,
      currentValue: null,
      isSet: false,
    },
  ],
  validationErrors: [],
  validationWarnings: [],
};
export const client = {
  getPlugins: async () => ({ plugins: [TELEGRAM_PLUGIN] }),
  updatePlugin: async () => ({ success: true }),
  startConnectorAccountOAuth: async () => ({ ok: true, authUrl: "https://telegram.org/oauth/mock" }),
  authorizeDiscordLocal: async () => ({ ok: true }),
  uploadBackgroundImage: async () => ({ url: "/api/media/mock-background.png" }),
  generateBackgroundImage: async () => ({ url: "/api/media/generated-background.png" }),
  getPermission: async (id) => ({ id, status: "not-determined", lastChecked: 0, canRequest: true, platform: "darwin" }),
  requestPermission: async (id) => ({ id, status: "granted", lastChecked: Date.now(), canRequest: true, platform: "darwin" }),
  openPermissionSettings: async () => true,
};
